application: waybetter-app
version: 2
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media/

- url: /static
  static_dir: static/

- url: /.*
  script: djangoappengine/main/main.py

