application: waybetter-app
version: dev
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /_ah/queue/deferred
#  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media/

- url: /static
  static_dir: static/

- url: /_ah/channel/.*
  script: ordering/channel_handler.py

- url: /extensions/notifier.crx
  static_files: static/extension/notifier.crx
  upload: static/extension/notifier.crx
  expiration: "10s"

- url: /extensions/updates.xml
  static_files: static/extension/updates.xml
  upload: static/extension/updates.xml
  expiration: "10s"

- url: /.*
  script: common/main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
#- ^(.*/)?index\.yaml
#- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?build\/.*
- ^(.*/)?intermediate\/.*
- ^(.*/)?publish\/.*

inbound_services:
- channel_presence

builtins:
- remote_api: on
#- appstats: on # uncomment to activate app stats