application: waybetter-app
version: dev # change to your dev-version for testing, and '1' for the live version.
runtime: python
api_version: 1

default_expiration: '365d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

- url: /media/admin
  static_dir: django/contrib/admin/media/

- url: /static
  static_dir: static/

- url: /_ah/channel/.*
  script: ordering/channel_handler.py

- url: /extensions/notifier.crx
  static_files: static/extension/notifier.crx
  upload: static/extension/notifier.crx
  expiration: "10s"

- url: /extensions/updates.xml
  static_files: static/extension/updates.xml
  upload: static/extension/updates.xml
  expiration: "10s"

- url: /.*
  script: djangoappengine/main/main.py

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?build\/.*
- ^(.*/)?intermediate\/.*
- ^(.*/)?publish\/.*

inbound_services:
- channel_presence

#builtins:
#- appstats: on # uncomment to activate app stats